### ISSUE TITLE
SMB2_CREATE_REQUEST_LEASE context is not handled properly in SMB2 reply

### ISSUE THREAD

**Issue by kvv81** [jborean93/smbprotocol#11]
https://github.com/jborean93/smbprotocol/blob/9c06fc5ce3eab3ce2fa8abcc55c5323baeecdc89/smbprotocol/create_contexts.py#L60

Please note that SMB2_CREATE_REQUEST_LEASE has exactly the same value as SMB2_CREATE_REQUEST_LEASE_V2 so you cannot use context name only as the unique key in CreateContextName.get_response_structure() . Since duplicated keys are still used to match lease v1 and lease v2, python always return lease_v2 response data structure, so when we have lease_v1 in Create Response we fail on unpacking the structure because lease_v2 is longer than lease_v1. See stack-trace of this problem below.

To handle this corner-case properly I propose to follow suggestion by Microsoft.
See [MS-SMB2] 2.2.14.2 SMB2_CREATE_CONTEXT Response Values:
SMB2_CREATE_RESPONSE_LEASE_V2  : This context value is the same as the SMB2_CREATE_RESPONSE_LEASE value; **the client differentiates these responses based on the value of the DataLength field**.

So I propose to pass context length ('buffer_data' length) to CreateContextName.get_response_structure() as the second parameter and if context name is SMB2_CREATE_REQUEST_LEASE then we should check also 'buffer_data' length to return proper response context structure (either lease V1 or V2).

Stack trace:
```
  File "test.py", line 394, in _open_file_with_lease
    file = self._open_file(file_name, desired_access=access_mask, create_contexts=ctx)
  File "test.py", line 298, in _open_file
    create_contexts_response = file.create(impersonation_level, desired_access, file_attributes, share_access,
    create_disposition, create_options, create_contexts, send)
  File "lib/python3.6/site-packages/smbprotocol/open.py", line 1012, in create
    return self._create_response(request)
  File "lib/python3.6/site-packages/smbprotocol/open.py", line 1043, in _create_response
    create_contexts_response.append(context.get_context_data())
  File "lib/python3.6/site-packages/smbprotocol/create_contexts.py", line 221, in get_context_data
    structure.unpack(self['buffer_data'].get_value())
  File "lib/python3.6/site-packages/smbprotocol/structure.py", line 118, in unpack
    data = field.unpack(data)
  File "lib/python3.6/site-packages/smbprotocol/structure.py", line 212, in unpack
    self.set_value(data[0:size])
  File "lib/python3.6/site-packages/smbprotocol/structure.py", line 199, in set_value
    parsed_value = self._parse_value(value)
  File "lib/python3.6/site-packages/smbprotocol/structure.py", line 351, in _parse_value
    int_value = struct.unpack(struct_string, value)[0]
struct.error: unpack requires a buffer of 2 bytes
```

**Comment by jborean93** [comment]
Ah I see what you mean, I never noticed that the values were the same for these. I'll look into this and hopefully create a new release soon.

**Comment by jborean93** [comment]
Thanks for reporting this issue, I've created a PR at https://github.com/jborean93/smbprotocol/pull/13 that hopefully solves the problem you are seeing. I also encountered a few other issues when trying to parse a lease response from the server.

One thing to note is that smbprotocol does not have a way to process the LEASE break message that can be sent by the server out of bounds. I'm not really sure whether that's an actual issue for your use case but it is something to be aware of.

**Comment by kvv81** [comment]
Thanks for PR, it looks like exactly what we needed!

As for the note - yes, we already discovered this issue before (when SMB server sends lease break outbound packet, smbprotocol library posts exception about unknown message ID=0xffffffffffffffff because this notification packet has no client request counter-part).
To handle this issue, we've implemented fast&dirty work-around to put 0xffffffffffffffff to the outbound packets list and extract it on waiting for lease break. However we can have more than one break packet in a while so correct approach should also use lease key as the key for storing this packet, thus more sophisticated change is needed for proper support of lease breaks...

**Comment by jborean93** [comment]
Yep, you are more than welcome to try and add it, I don't fully understand the purpose and the need for it so I'm probably not the best person to try and implement it. Do you have a use case to illustrate when a lease is useful and the general worflow you are following?
