### ISSUE TITLE
How to connect to a samba share?

### ISSUE THREAD

**Issue by jacob-levit** [jborean93/smbprotocol#131]
Hello! Thanks for your library. Can you please tell me how to connect to the shared samba resource?

```
server = "192.168.213.238"
port = 445
username = r"CO\Administrator"
password = "password"
share = "exchange"
dir_name = "1"

connection = Connection(uuid.uuid4(), server, port)
connection.connect()

session = Session(connection, username, password)
session.connect()

tree = TreeConnect(session, r"192.168.213.238/exchange")
tree.connect()
dir_open = Open(tree, dir_name)
dir_open.create(
    ImpersonationLevel.Impersonation,
    DirectoryAccessMask.GENERIC_READ | DirectoryAccessMask.GENERIC_WRITE,
    FileAttributes.FILE_ATTRIBUTE_DIRECTORY,
    ShareAccess.FILE_SHARE_READ | ShareAccess.FILE_SHARE_WRITE,
    CreateDisposition.FILE_OPEN_IF,
    CreateOptions.FILE_DIRECTORY_FILE
)

```

`smbprotocol.exceptions.BadNetworkName: Received unexpected status from the server: The specified share name cannot be found on the remote server. (3221225676) STATUS_BAD_NETWORK_NAME: 0xc00000cc`

Can you please tell me why this is happening?

**Comment by jborean93** [comment]
In case you didn't figure it out the TreeConnect share name is in the format `\\server\share` so doing `r"\\192.168.213.238\exchange"` should work. I'm unsure what the overall goal is for the opened tree but you are better off using the high level API under `smbclient` which makes these calls so much easier to use.

```python
import smbclient

smbclient.register_session("192.168.213.238", username=username, password=password)

smbclient.listdir(r"\\192.168.213.238\exchange\1")
```

There are a whole bunch of methods under `smbclient` and `smbclient.path` that replicates the functionality of `os` and `os.path` but for SMB paths.

**Comment by jacob-levit** [comment]
Thanks for the answer! The tree is needed to set security attributes on directories or files.

**Comment by jacob-levit** [comment]
Yes, I looked at your example at the link.
https://gist.github.com/jborean93/c4d8db1db14297de1c9a268084e89d36
I'll do it as in that example.
Thanks.

**Comment by jborean93** [comment]
Is there a reason why you've reopened this? Just wanting to double check there is no other question you had.

**Comment by jacob-levit** [comment]
Yes, could you please tell me, how to set security descriptors on a file/directory using your library? I can't figure out, how to do it at all.

**Comment by jborean93** [comment]
There's no easy way currently and there is an open request to implement it https://github.com/jborean93/smbprotocol/issues/52. It *is* possible but it will be quite verbose and would solely operate on security identifiers and not names. Essentially you need to send a `SMB2SetInfoRequest()` for `SMB2_0_INFO_SECURITY` where the additional information is the security descriptor buffer as defined in `smbprotocol.security_descriptor.SMB2CreateSDBuffer`.

**Comment by jacob-levit** [comment]
Thanks for the answer. I understand.

**Comment by jborean93** [comment]
Closing as per the above, #52  should be followed if you are interested in a high level API for modify ACLs on a file/dir.
