### ISSUE TITLE
 The specified share name cannot be found on the remote server.  - bad share path?

### ISSUE THREAD

**Issue by wennaspeedy** [jborean93/smbprotocol#132]
Hi, I am trying to test smbprotocol for files uploading.

My path to share:
`share = r"\\10.31.4.14\14zone\!O14-1\!reporting\Týdenní hlášení (PaPo)"`

I got the example from git folder and I have weird error.

Server returns me:
```
The specified share name cannot be found on the remote server. 
STATUS_BAD_NETWORK_NAME
```

If I try part of the share path with standard chars, server returns me :

`share = r"\\10.31.4.14\14zone"`

 `A process has requested access to an object but has not been granted those access rights.` - **This is right.**

I thing problem is in special characters like ! .

Could you provide me a workaround?

I tried mount this share (`\\10.31.4.14\14zone\!O14-1\!reporting\Týdenní hlášení (PaPo))` in linux as drive and it works.

**Comment by adiroiban** [comment]
Hi,


What is the correct name of the share: `14zone!O14-1!reporting` ?

Why are you escaping the exclamation marks?

I think the URL should be:

```
share = r"\\10.31.4.14\14zone!O14-1!reporting\Týdenní hlášení (PaPo)"
```

Can you provide a full example?

Thanks!

**Comment by wennaspeedy** [comment]
Sorry, \\10.31.4.14\14zone\!O14-1\!reporting\Týdenní hlášení (PaPo) is correct path.

**Comment by wennaspeedy** [comment]
```
server = "10.31.4.14"
port = 445
username = "..."
password = "..."
share = r"\\10.31.4.14\14zone\!O14-1\!reporting\Týdenní hlášení (PaPo)"
file_name = "file-test.txt"

connection = Connection(uuid.uuid4(), server, port)
connection.connect()

try:
    session = Session(connection, username, password)
    session.connect()
    tree = TreeConnect(session, share)
    tree.connect() #failed on this
...
```

I tried:
`share = r"\\10.31.4.14\14zone\!O14-1\!reporting\Týdenní hlášení (PaPo)"` - The specified share name cannot be found on the remote server. 

`share = r"\\10.31.4.14\14zone\!O14-1\!reporting"` - The specified share name cannot be found on the remote server. 

`share = r"\\10.31.4.14\14zone\!O14-1"` - The specified share name cannot be found on the remote server. 

`share = r"\\10.31.4.14\14zone" `- Server find this share


Share includes exclamation marks.

**Comment by jborean93** [comment]
A share/tree is just the `\\server\share` portion, the rest are just dirs in that share. The only exception to this rule is for things like DFS which isn't fully supported in the low level API. Basically you want to connect to `\\10.31.4.14\14zone` and then use `Open(tree, r"!O14-1\!reporting\Týdenní hlášení (PaPo)")` for any operations on that path.

This is all handled by the high level API in `smbclient`, is there a reason why you are using the low level one?

**Comment by adiroiban** [comment]
As commented by Jordan you need to use this share name.
```
share = r"\\10.31.4.14\14zone\"
```

and  once you have the tree you can open the path inside the  share (without the leading separator)

```
handler = Open(tree, r'!O14-1\!reporting\Týdenní hlášení (PaPo)')
```

I hope it help.

-------

I am using the low-level code as I want a more detailed control over the connections  and the threads.. and I am working to integrate the code with async/no-blocking/non-threading code :)

**Comment by wennaspeedy** [comment]
Thank you guys. My fault, I didn't get it from example. I will try path with handler and also high-level api. I will let you know.

**Comment by wennaspeedy** [comment]
I tried high-level uploading with simple example and works like charm. Thank you for your time!
