### ISSUE TITLE
Connection fails when username has more than one hyphen (`-`) in it.

### ISSUE THREAD

**Issue by Bargenish** [jborean93/smbprotocol#156]
When trying to create a session with a username that contains more than one hyphen, an exception is raised.

The username (`AA-user-with-hyphens`) is valid and the connection should be established successfully.

traceback:
```python
Traceback (most recent call last):
  File "<string>", line 8648, in main
  File "<string>", line 8556, in list_dir
  File "<string>", line 8476, in create_session
  File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 359, in register_session
    session.connect()
  File "/usr/local/lib/python3.9/site-packages/smbprotocol/session.py", line 292, in connect
    response = self.connection.receive(request)
  File "/usr/local/lib/python3.9/site-packages/smbprotocol/connection.py", line 931, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.SMBResponseException: Received unexpected status from the server: Unknown error. (3221225584) UNKNOWN_ENUM: 0xc0000070
```

**Comment by jborean93** [comment]
The error you get here relates to `STATUS_INVALID_WORKSTATION` which essentially means the account is not authorized to logon onto the target host in question. In AD these settings are under the `Log On To` option of the user account

![image](https://user-images.githubusercontent.com/8462645/144506329-9ebe7e61-d6cc-4a84-a347-54aa2203d22a.png)

I remember this being a complicated option as it actually applies to the workstation specified in the NTLM token which is the client host (one running smbprotocol).

**Comment by Bargenish** [comment]
@jborean93 Thanks for replying so quickly!
Let me check with the customer, not sure that's the case here but I'll double check. will update here soon.
Thanks!

**Comment by Bargenish** [comment]
Customer mentioned the issue is resolved.
Thanks for looking into it!!
