### ISSUE TITLE
STATUS_INVALID_PARAMETER: 0xc000000d

### ISSUE THREAD

**Issue by RalfKraemer1** [jborean93/smbprotocol#165]
Hi, I am using a programme to store readings on an OpenMediavault 5 Nas. This worked great for a long time. After updating the NAS, I now get an "unhandled smbprotocol.exceptions.InvalidParameter" error on access.

I have created a log file with this short code.
A connection to other devices works.

import smbclient
import logging

file_log = logging.FileHandler('smb.log')
file_log.setLevel(logging.DEBUG)
file_log.setFormatter(logging.Formatter('%(asctime)s - %(name)s - %(message)s'))

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
logger.addHandler(file_log)
    

smbclient.ClientConfig(username="user", password="password")
smbclient.register_session("nas", username="user", password="password")
for filename in smbclient.lscandir(r"\\nas\data"):
    print(filename)

Is there something wrong with the authentication there?
With ntlm as authentication it doesn't work either?

[smb.log](https://github.com/jborean93/smbprotocol/files/8160878/smb.log)
)

Thanks for Helping!

**Comment by jborean93** [comment]
Based on your logs and description the connection is failing even before it gets to the authentication attempt. The client is sending the SMB Negotiate request but the server is immediately responding with an invalid parameter failure indicating it failed to process the negotiate request. I'm unfamiliar with OpenMediaVault but having a brief read online indicates it uses SAMBA for the SMB server side. This repo uses SAMBA as part of the CI integration tests https://github.com/jborean93/smbprotocol/blob/master/build_helpers/samba-setup.sh on Linux and I know that is passed just fine.

If you can share the exact version of OpenMediaVault that you are using I'm happy to try and set up a test environment to play with it. The only other thing you can do is to try and enable server side logging to figure out why it's rejecting the negotiate request. Right now it's saying there was an invalid parameter but the error codes are very vague and it doesn't convey what parameter was the actual problem here.

**Comment by jborean93** [comment]
Thanks for the info, nothing is jumping out in the logs so I'll have to find some time to replicate your setup and test it out.

**Comment by RalfKraemer1** [comment]
Hello, 
is there anything what i can do to Help you?
Thanks a lot

Ralf

**Comment by jborean93** [comment]
I've just installed OpenMediaVault 5.6.13-1 and cannot replicate the problem. I also installed the latest updates to bring it to 5.6.26-1 and still no luck. I've verified that the version of Samba that is being run is at version 4.9.5 just like your setup.

Accessing the share works just fine and the console shows the active session

```python
>>> import smbclient
>>> smbclient.listdir(r'\\192.168.122.12\my_share', username='smbuser', password='smbpass')
['my_file.txt', 'testing']
```

![image](https://user-images.githubusercontent.com/8462645/156941664-5ff02018-4812-49fc-93f1-ea398463c8f9.png)

I'm honestly have no idea why your setup isn't working, it's failing with the first SMB packet the Negotiate message. This message is essentially the client telling the server what features it supports and there is no encryption, signing, or authentication being done at this phase.

At this point there's not much else I can do to try and fix the problem. My only recommendation is to see if you can increase the log level for Samba and see if anything else appears in the logs when trying to connect to the host. I would also try and verify whether other clients can connect to the share. Bare in mind smbprotocol/smbclient uses some fairly new features that have only been introduced with Server 2022/Windows 11 so if you have those on hand it would be good to test them out.

**Comment by xyxz-web** [comment]
I'm having a very similar problem when connecting using the low level API and specifiying the protocol version.
The following at least connects, but file upload using smbclient.shutil.copy is extremly slow:
``` 
    import smbclient
    from smbprotocol import Dialects
    from smbprotocol.connection import Connection   

    connection = Connection(uuid.uuid4(), "myserver.com", 445)
    connection.connect(Dialects.SMB_3_0_2)
    connection_cache = {"myserver.com:445": connection}

    smbclient.register_session(
       "myserver.com",
        username="myuser",
        password="mypassword",
        connection_cache=connection_cache
    )```

Would be great if there was an option to specify protocol version on the high level client directly.
Also I wonder what could cause the extremely slow speed of just a few kilobytes per second.

**Comment by xyxz-web** [comment]
copy speed can be greatly increased by increasing the buffer size, e.g.:
smbclient.shutil.copyfile(local_file, remote_file, connection_cache=connection_cache, buffering=65536 * 128)

**Comment by jborean93** [comment]
Closing as this is not something I can replicate after trying the same versions as OP. Without seeing more info from the Samba side as to why it's rejected the Negotiate message there's not much else I can do.

As for exposing the dialect option on the high level API I'm not a fan of this. The client shouldn't care about what dialect it offers and should always try and offer the latest available. If there is a performance issue with using a newer dialect then that should be investigated separately.
