### ISSUE TITLE
ModuleNotFoundError: No module named 'smbclient'

### ISSUE THREAD

**Issue by HempWeed** [jborean93/smbprotocol#166]
I know this seems like a stupid question but I have pip installed smbprotocol, uninstalled it, reinstalled it, uninstalled python, reinstalled python, tried older versions, tried different machines, tried macOS but I cannot get the smbclient module to be acknowledged by any IDE. What can I do, hope there is a simple fix, sorry for being a pain in the ass.

Have a great day :)

pip freeze shows this, among other results...
<img width="152" alt="Screenshot 2022-03-03 at 12 26 48" src="https://user-images.githubusercontent.com/34575058/156564544-b4289bdc-aa67-42d5-8d90-eca692535b5d.png">
<img width="394" alt="Screenshot 2022-03-03 at 12 28 26" src="https://user-images.githubusercontent.com/34575058/156564850-04b51669-c51c-4125-af47-8a39510c0936.png">

**Comment by jborean93** [comment]
I'm unsure sorry, this most likely means your IDE is not using the same Python/venv that the `smbprotocol` was installed on or it is using a different `PYTHONPATH` that excludes where `smbclient` is installed on. There's not much else I can help you wish here sorry.
