### ISSUE TITLE
Getting STATUS_FS_DRIVER_REQUIRED

### ISSUE THREAD

**Issue by ccwillia** [jborean93/smbprotocol#174]
Trying to use smbclient from osx.  I am able to execute mkdir, remove, open with success.  When trying to use rename/replace i get an STATUS_FS_DRIVER_REQUIRED.  Do i need to disable DFS some how?  I looked for example of rename/replace in the low-level examples using smbprotocol but wasn't able to find one to try.

**Comment by ccwillia** [comment]
I have done some more testing against a couple other SMB shares.   It appears this issue is related to DFS.  The share where the rename/replace commands are not working returns `capabilities = (8) SMB2_SHARE_CAP_DFS` which then sets `is_dfs_share` to True.  If i edit the code and flip `is_dfs_share` to False the rename/replace operations work.   It would be great to have a flag that could be set in either `register_session` or `ClientConfig` to force `is_dfs_share` to False

**Comment by ccwillia** [comment]
I ended up disabling DFS on the storage and now rename/replace are working.

**Comment by jborean93** [comment]
DFS is a bit confusing but it sounds like we potentially need to just ignore this error if attempting to do a DFS referral request. Disabling it on the share/server is definitely a workaround at this point in time.

Is it possible to share what SMB server you are using in your scenario so I can try and test this out myself?

**Comment by ccwillia** [comment]
Sorry, the SMB server is a private cloud

**Comment by jborean93** [comment]
No worries, i was more looking for the product, like AWS FS or something like that. Still understand if you can’t share that as well just curious.

**Comment by jborean93** [comment]
Closing as OP had a workaround in place and without further info on the environment or a way to replicate I cannot do much else to help.

**Comment by jepperaskdk** [comment]
I'm getting this error as well.

I have created a shared folder on my laptop in C:\Shared (Windows 11). I'm then attempting to e.g. `listdir` from my Ubuntu WSL VM:
```
smbclient.listdir(r"\\[IP]\Shared", username="[USER]", password="[PASSWORD]")
```
Throws this error:
```
smbprotocol.exceptions.FSDriverRequired: Received unexpected status from the server: A volume has been accessed for which a file system driver is required that has not yet been loaded. (3221225884) STATUS_FS_DRIVER_REQUIRED: 0xc000019c
```
