### ISSUE TITLE
Error importing smbclient

### ISSUE THREAD

**Issue by julianbenavides** [jborean93/smbprotocol#18]
Hi @jborean93, thanks for your contribution.

I was trying to test the high-level SMB connection using smbclient and got this error:

> import smbclient
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'smbclient'

I installed smbprotocol via pip

**Comment by martinhoefling** [comment]
Have you installed the prerelease version? 1.0.0b1? Or the current stable 0.2.0?

**Comment by julianbenavides** [comment]
Hi @martinhoefling, I did not check at install time, but this is the output when I the pip install command again:

> C:\WINDOWS\system32>pip install smbprotocol
> Requirement already satisfied: smbprotocol in c:\program files\python37\lib\site-packages (0.1.1)
> Requirement already satisfied: six in c:\program files\python37\lib\site-packages (from smbprotocol) (1.11.0)
> Requirement already satisfied: cryptography>=2.0 in c:\program files\python37\lib\site-packages (from smbprotocol) (2.7)
> Requirement already satisfied: ntlm-auth in c:\program files\python37\lib\site-packages (from smbprotocol) (1.2.0)
> Requirement already satisfied: pyasn1 in c:\program files\python37\lib\site-packages (from smbprotocol) (0.4.7)
> Requirement already satisfied: asn1crypto>=0.21.0 in c:\program files\python37\lib\site-packages (from cryptography>=2.0->smbprotocol) (0.24.0)
> Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\program files\python37\lib\site-packages (from cryptography>=2.0->smbprotocol) (1.12.2)
> Requirement already satisfied: pycparser in c:\program files\python37\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.0->smbprotocol) (2.19)

**Comment by martinhoefling** [comment]
`pip freeze` should give you all installed packages with versions

**Comment by julianbenavides** [comment]
Thanks for that:

> smbprotocol==0.1.1
