### ISSUE TITLE
Issuing commands / printing

### ISSUE THREAD

**Issue by paulschmeida** [jborean93/smbprotocol#185]
Hi.
I am trying to figure out how to replicate this functionality of smbclient:
`smbclient -U username \\\\server\\printer_share -c "print file.txt"`

I've looked through files but I can't figure out how to do it with this library and I would like to avoid using subprocess for compatibility reasons.

**Comment by adiroiban** [comment]
I guess that first, you can try to use the low-level smbprotocol code to open the printer and write the file to it.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/8122dfdb-d11f-44e4-91d6-f290d26e1db0

For sending a file to a printer, the application [opens](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/b1b7cc8a-4d24-4701-bc3f-220b543ceef8#gt_0d572cce-4683-4b21-945a-7f8035bb6469) the root of a print [share](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/b1b7cc8a-4d24-4701-bc3f-220b543ceef8#gt_a49a79ea-dac7-4016-9a84-cf87161db7e3), writes data, and closes the file. The semantics and parameters are the same as specified in section [3.2.4.3](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/448cb979-7321-4598-89df-e5c97135b566), except that TreeConnect.ShareName will be the name of a printer share, and the share relative path MUST be NULL.

**Comment by jborean93** [comment]
Yea this is theoretically possible and based on the docs you might just be able to do

```python
import smbclient

with smbclient.open_file(r"\\server\printer_share", mode="xb", buffering=0) as fd:
    fd.write(file_bytes)
```

But even then I've never tested this or are sure if it will work.

**Comment by paulschmeida** [comment]
Hi, just wanted to confirm that it works exactly as you described @jborean93 :) I can even skip having the files on the filesystem and just pass `io.BytesIO()` objects to it.
