### ISSUE TITLE
Why is directory not seekable? There's a file index that sets the position of the directory stream

### ISSUE THREAD

**Issue by diwu1989** [jborean93/smbprotocol#19]
https://github.com/jborean93/smbprotocol/blob/b6abd4ae092ee01a3ab2a6b8999237b293151b90/smbclient/_io.py#L506

In Posix, a directory can have `telldir` and `seekdir` to move around in the directory stream.
Can we make the directory also seekable?

**Comment by jborean93** [comment]
Do you have an example Python script that demonstrates this? I know you can use `os.open('dir')` but that just returns an int for the file descriptor. Also what are you trying to achieve here?

**Comment by diwu1989** [comment]
I have a folder that has over 1 million children.
I want to iterate through them in batches, and be able to seek directly to a resume offset.
The underlying SMB protocol allows the offset to be passed around, and as long as the directory itself doesn't mutate in between, I should be able to pick up the scan at a specific offset.

**Comment by jborean93** [comment]
Yep I understand that [SMB2 Query Directory](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/10906442-294c-46d3-8515-c277efe1f752) has a `FileIndex` field which seems to be what you are looking for.

From your comment

> In Posix, a directory can have telldir and seekdir to move around in the directory stream.

It sounds like you were saying that when you create a Python directory fd you can call the `seek()` and `tell()` methods on that object. But now I understand you are talking about the actual POSIX calls themselves. The reason why I was confused is that `smbclient` is designed to be a copy of the existing Python `os` and `shutil` methods when it comes to the file system.

The reason why a `SMBDirectoryIO` is set as not seekable is that they aren't seekable in the traditional `read()` and `write()` way of working present in Python. I could have somehow hook this in so a read would read the next directory entry and change the offset to the `FileIndex` returned but this comes to the next problem which is that there are 6 types of information structures that can be returned. From what I remember the index returned is also not just a simple number but a byte offset inside the directory. This makes it difficult for an end user to seek it manually themselves as they would need to know how the offset is calculated.

Finally the Microsoft SMB server implementation does not support resuming an enumeration of a directory as per [footnote 353 of MS-SMB2]((https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/a64e55aa-1152-48e4-8206-edd96444e7f7#Appendix_A_353)

> Windows-based servers do not support resuming an enumeration at a specified FileIndex. The server will ignore this flag.

This means that Microsoft won't support the scenario you are hoping for but I am unsure if maybe it is supported by Samba or some other 3rd party implementation.

In the end I think this might have be something that is just dealt with in the low level API. You can still use `smbclient` to create an open under a context manager with the following

```
import smbclient

with smbclient.open_file(r'\\server\share\directory', mode='rb', buffering=0, file_type='dir') as fd:
    raw_fd = fd.fd  # This is the smbprotocol.Open() for the directory
```

**Comment by diwu1989** [comment]
Can we expose specific API for SMBDirectoryIO class to retrieve a specific file index and seek back to it?
I'm using it against enterprise Dell EMC Isilon storage appliance over SMB. Internally, they are running custom samba server.

**Comment by jborean93** [comment]
If you do

```
import smbclient

# Opening in binary, with buffering=0 and specifying the file_type='dir' opens the raw SMBDirectoryIO object
with smbclient.open_file(r'\\server\share\directory', mode='rb', buffering=0, file_type='dir') as fd:
    # From there you can access the smbprotocol Open object of the dir through the fd property
    raw_open = fd.fd

    query_result = raw_open.query_directory(...)

    # query_result is a list of directory information objects as defined by the info_type in query_directory
    for entry in query_result:
        file_index = query_result['file_index'].get_value()
        print(query_result['file_name'].get_value().decode('utf-16-le'))
```

The `query_directory` method is defined in [smbprotocol.open](https://github.com/jborean93/smbprotocol/blob/26b42e28371d23a1d63502edade06eb6764216c4/smbprotocol/open.py#L1434). You can specify the file index here as well as other low level options for the query directory request sent to the server.

In saying that, the Microsoft SMB server implementation does not support seeking on a file index but I have no idea about Samba or other 3rd party implementations.

**Comment by diwu1989** [comment]
This is pretty helpful, thanks!

**Comment by jborean93** [comment]
Is there anything else you wanted to add to this? My feeling is that this shouldn't be part of the low level interface and smbclient still provides you with an easy way to access the raw open to achieve what you need on certain SMB servers.
