### ISSUE TITLE
New release on PyPI?

### ISSUE THREAD

**Issue by ForeverEndeavor** [jborean93/smbprotocol#194]
Hey there! Any possibility of creating a new release on PyPI with the DFS changes made in the last several months? We use your library extensively and wanted to test the DFS changes that would fix some issues we've been seeing; would be easier for us to upgrade the library instead of building it from git.

**Comment by jborean93** [comment]
Sorry about the delay, I'm looking at pushing a new release this week.

**Comment by jborean93** [comment]
A new release at 1.10.0 has been published on PyPI. Sorry for the delay here.
