### ISSUE TITLE
 Problem copying smb file

### ISSUE THREAD

**Issue by lulusmxxx** [jborean93/smbprotocol#208]
Hello, I have a problem when I want to copy a file from my post to another post in smb. I have this error message although the path is absolutely correct, do you have a solution?
![capt2](https://user-images.githubusercontent.com/113111499/218420339-f3386b78-f55c-4fc5-a2f5-56f856e4ab89.png)

**Comment by lulusmxxx** [comment]
Ok I think I understood you can't copy from one host to a different host. Do you have a solution to do this?

**Comment by jborean93** [comment]
Using `copyfile` directly on `smbclient` is limited to a copy on the same host but you can use `smbclient.shutil` with `copy`, `copy2`, `copyfile`, `copyfileobj` which should support copying files between different hosts (including local). Also keep in mind to use `r""` strings for all your paths with a backslash in them (or remember to double them up if you don't).
