### ISSUE TITLE
Porting to nodejs / typescript

### ISSUE THREAD

**Issue by eadoking** [jborean93/smbprotocol#218]
Hey guys,

I am planning to port this library to nodejs / typescript as a pure implantation / minimum dependency which could run on lambda/azure / google functions as a server-less world.

Currently, there is so many implementations for the same protocol on nodejs, there are devided into two categories.

1- based on old implementation https://github.com/bchelli/node-smb2 (which is not maintained anymore)
2- have to install smbclient on linux (work only on EC2/Compute engines .. ) or lambdas as a docker, both not what is needed.

The new work supposed to be based on your implementation +this old one on nodejs https://github.com/bchelli/node-smb2 

The new work will also be an MIT license or compatible license with open-source and will be published on npm registry. 

Any suggestions? ideas? 

Do you agree to this porting?

Regards, Eid

**Comment by jborean93** [comment]
My main advice would be to make sure you work with modern standards like signing/encryption as well as SMB 3.1.1. Ensure you cover the basics and don't need to fallback to the more insecure stuff making your API a security issue. YOu can port whatever you like but remember this is a Python library and not javascript.
