### ISSUE TITLE
`reset_connection_cache` not deleting on disconnection failure.

### ISSUE THREAD

**Issue by NarinderS** [jborean93/smbprotocol#248]
The `reset_connection_cache` function doesn't seem to delete a connection if it fails to disconnect first. So for example, if the connection had the wrong credentials, it sits around in the cache forever, unless deleted via `delete_session`.

The simplest solution would be to delete the connection, no matter if disconnection was successful, but I'm not sure if that would cause other issues.

**Comment by jborean93** [comment]
Thanks for the report, I'll try and fix it up when I get to looking at the current log of issues soon.

**Comment by jborean93** [comment]
Fixed by https://github.com/jborean93/smbprotocol/pull/291
