### ISSUE TITLE
On disconnectt wait for msg_worker thread to end.

### ISSUE THREAD

**Issue by adiroiban** [jborean93/smbprotocol#254]
This should not be an issue in production.

It's just something to help with the automated tests.

For the automated tests, I have some extra checks to make sure the tests are not generating "stray" threads.

Since smbprotocol is not waiting for the `msg_thread-` to end on disconnect my cleanup checks is "flaky" and sometimes it reports that the `msg_worker-` thread was left unclosed by the test.

The `msg_worker` will enventuall close

It would be nice to have something like `self._t_worker.join(timeout=5)` at the end of `smbprotocol.connection.Connection.disconnect`

https://github.com/jborean93/smbprotocol/blob/37512ee0648ad64f98755833382fea790d9b2df6/src/smbprotocol/connection.py#L934-L949

Thanks

**Comment by adiroiban** [comment]
Let me know if this is something you would like to have in the code and I can send a PR.

Also, have you seen my comment from https://github.com/jborean93/smbprotocol/pull/80#issuecomment-1824970873  this is another case in which the automated tests are failing.

**Comment by jborean93** [comment]
Feel free to open a PR, I started a mini refactor of the TCP transport stack in the branch https://github.com/jborean93/smbprotocol/tree/socket-refactor. This was in preparation of supporting other transports like QUIC and to try and remove of the multithreading complexity that currently exists. I still plan on getting back to it at some point but I don't know when so if you have a PR to try and improve the current situation I'm definitely all for it.
