### ISSUE TITLE
Add support for DFS shares

### ISSUE THREAD

**Issue by Fen0l** [jborean93/smbprotocol#26]
Hello,

I am getting this error when I try to used it with my File Server.  On the Microsoft doc it seems related to STATUS_PATH_NOT_COVERED. Im trying with the full DFS share name but impossible. Is smbprotocol support DFS ? Or any idea of what should I used ?

`smbprotocol.exceptions.SMBResponseException: Received unexpected status from the server: (3221226071) UNKNOWN_ENUM: 0xc0000257`

Impossible to list the root of any share and any directories from share.

Thank for your hints :)

**Comment by jborean93** [comment]
Unfortunately smbprotocol does not yet support DFS, it may work in some situations but things like referrals of when the DFS path is for a folder/file on another server it will fail. It's something I do want to add at some point in the future but this is not a trivial task. Just looking at https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsc/1ff7d611-ba19-49fb-95f4-7c5358b86834 shows you how many branching steps there are.

I will edit the issue title to better reflect this as a request to support DFS.

**Comment by exislow** [comment]
DFS support would be great. Any chance for an implementation?

**Comment by jborean93** [comment]
Not anytime soon unless someone is willing to do it sorry. I’ve got 3 other side projects I’ve started and want to complete before even looking at this.

**Comment by exislow** [comment]
Too bad. Do you maybe know any Python alternative, which can handle DFS smb shares?

**Comment by jborean93** [comment]
The only other python library I know that does SMB is [pysmb](https://github.com/miketeo/pysmb) but that does not support it.

DFS support is quite complex and not easy to implement. There’s a reason why it doesn’t work in a lot of 3rd party libraries. You can try and resolve one of the time servers behind your DFS name then you can access it like any normal SMB server.

**Comment by exislow** [comment]
Okay, I understand.

I tried this but without any success somehow. How would you revolve a time server in DFS? For example:

- MyDFS URL is: big.corp
- Share Name: SHAREFS
- Path to access: MyFolder
=> \\big.corp\SHAREFS\MyFolder

How do I a resolve the time server to MyFolder and how do I access it later? I am happy about every hint!

**Comment by jborean93** [comment]
Unfortunately I don't know of a way to dynamically get that info without actually implementing DFS support itself. You can get it with something like [Get-DfsnFolderTarget](https://docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=win10-ps) on Windows PowerShell but that needs to be run separately and doesn't help if the server ever changes underneath.

**Comment by exislow** [comment]
I am on a linux system. This is too bad, but thank you anyway.
