### ISSUE TITLE
mkdir -p recursive directory create

### ISSUE THREAD

**Issue by habhabhabs** [jborean93/smbprotocol#270]
@jborean93 and the maintainers, thanks for making this project alive. It is very helpful working with SMB shares on Python3.

I'm working on a AWS Lambda automation and would benefit from having `mkdir -p` when creating new directories. 

From my observation, `mkdir` only creates on the first level. If I want to create child of child folders I have a challenge.

Would the development of this feature be part of the feature pipeline? Thanks

**Comment by adiroiban** [comment]
Hi Alex.

I think that mkdir is designed to work the same way as [os.mkdir](https://docs.python.org/3/library/os.html#os.mkdir)

I think that you are looking after `smbclient.makedirs` which is the equivalent of [os.makedirs](https://docs.python.org/3/library/os.html#os.makedirs)

**Comment by habhabhabs** [comment]
@adiroiban thanks mate, you're a gem! It works. 

Proceed to close.
