### ISSUE TITLE
Any way to list shares of an SMB server after creating session?

### ISSUE THREAD

**Issue by nirabhronz** [jborean93/smbprotocol#278]
It seems in ubuntu we can use `smbclient -L <server>` to view the list of shares. is there any equivalent for achieving this in python code running on linux?

**Comment by adiroiban** [comment]
See https://github.com/jborean93/smbprotocol/issues/118

I think that this is a duplicate.

**Comment by nirabhronz** [comment]
Cool, thanks for the direction
