### ISSUE TITLE
SMBDirEntryInformation.last_write_time is of type date, expected a datetime

### ISSUE THREAD

**Issue by christianknoepfle** [jborean93/smbprotocol#279]
Hi,

I was wondering why the `SMBDirEntryInformation.last_write_time` is defined as `date` and not `datetime`. All other *_time fields are defined as `datetime`. I just came across the issue, because intellij highlighted that as a warning in my code where I use a lot of typing. 

When running some tests the field value is a `datetime`, so I would assume that this is a typo. Right or Wrong?

I am using the latest smbclient 1.13.0

Thanks and best regards

Christian

**Comment by jborean93** [comment]
Thanks for the bug report and even more thanks for the PR that fixes this!

**Comment by jborean93** [comment]
Fixed by https://github.com/jborean93/smbprotocol/pull/280
