### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by the-suspect2** [jborean93/smbprotocol#29]
I would like to get the list of files present in a network share. Seeing how smbprotocol replicates the `os` and `os.path` functions, I've tried to modify a piece of code that uses os.scandir, so it uses smbclient.scandir instead.

The piece of code (which works when using `os.scandir` instead):
```
with smbclient.scandir(r"\\server\share\directory", username=network_username, password=network_password) as dir_contents:
	for f in dir_contents:
		fileList_array[f.name] = f.stat().st_mtime
```

Upon running, it throws the following error:
```
Traceback (most recent call last):
  File "<pyshell#42>", line 1, in <module>
    with smbclient.scandir(r"\\server\share\directory", username=network_username, password=network_password) as dir_contents:
AttributeError: __enter__
```

Using Python 3.7.0

**Comment by P-Muench** [comment]
scandir returns a generator. Try
```
for f in smbclient.scandir(path):
    fileList_array[f.name] = f.stat().st_mtime
```

With statements require requires that an object is returned that supports the context management protocol, requiring __enter__ and __exit__ methods. For more info, see PEP343 ([https://docs.python.org/2.5/whatsnew/pep-343.html](url))

**Comment by jborean93** [comment]
Sorry I thought I replied to this earlier, @P-Muench is correct, `smbclient.scandir` is a generator not a function with `__enter__` and `__exit__` so it can't be used with the `with ...` statement. While I believe `os.scandir` can work with either this is not something I implemented in smbclient so please use the for loop.
