### ISSUE TITLE
Error in connection.py; not specifying timeout properly

### ISSUE THREAD

**Issue by pacmanoth** [jborean93/smbprotocol#3]
connection.py, line 1354 should read 
        response = self.receive(request, timeout=timeout)

You are currently passing-in the timeout as though it were the Wait=True parameter

**Comment by jborean93** [comment]
Sorry about the wait, you are right and I should have an update for this sometime soon. Thanks for the pickup.

**Comment by jborean93** [comment]
Fixed with https://github.com/jborean93/smbprotocol/releases/tag/v0.1.1
