### ISSUE TITLE
Can encryption be enforced globally?

### ISSUE THREAD

**Issue by panchoop** [jborean93/smbprotocol#301]
The README.md indicates that  "Message encryption is set to True by default and needs to be overridden when creating a Session object for the older dialects.", but investigating the script, it does not seem to be the case (Below [1] I wrote my deduction, if it is of any use)

I am aware that I can enforce encryption by using: 

`smbclient.register_session("server.name", username="xxx", password="xxx", auth_protocol="ntlm", encrypt=True)`

but it happened that after sending my first request, the script contacted another 3 servers, which lead to an error. 
To ensure encryption, one also has to register each of the sub-servers, as "other.server.name", "other2.server.name", etc. 
Then it works.

The issue I see is that this might not be sustainable, as these other servers where requested by the first one, and if these servers change, the code will break.

I am aware that it is possible to globally configure using `ClientConfig`, which would avoid the errors generated by contacting new servers, but all the communications to unregistered servers are unencrypted and I would like to avoid that.

As a side request, it could be useful for the logs to indicate whether or not the communication is encrypted, there seem to not be any indication of it. 

Thanks!

---------------

[1]:
I configured a connection via
`smbclient.ClientConfig(username="xxx", password="xxx", auth_protocol="ntlm")`

Which looking at the source code, creates a session without the "encrypt" key argument, and the default value for encrypt in the get_smb_tree function is "encrypt=None".

Additionally, looking at runtime values I see that:
* It uses dialect SMB_3_1_1 -> server supports encryption
* There are no SMB2_SESSION_FLAG_ENCRYPT_DATA from the server
* the Session object has the field encrypt_data = False.

**Comment by panchoop** [comment]
I realized that encryption can be enabled at the function level, by doing

`smbclient.listdir(path, encrypt=True)`

This was mentioned in the documentation and I misunderstood it.

I apologize for the noise, I'm closing this.

**Comment by jborean93** [comment]
Thanks for sharing the solution!
