### ISSUE TITLE
_pool.py > register_session() exceptions

### ISSUE THREAD

**Issue by Breinich** [jborean93/smbprotocol#306]
Hi,

I'm interested in what type of exceptions should I expect during calling first the ClientConfig() constructor and then the register_session() function, if it fails to set up the connection, either because of the host is not reachable or bad credentials have been supplied.

I tried to dig deeper a bit into the underlying code system, but I haven't found any answer for my question yet, so I thought it'd be faster to ask it.

**Comment by jborean93** [comment]
There's probably a few exceptions

+ `SMBException` can be raised for a myriad of reasons, there are some inherited types raised for more specific reasons like
  + `SMBAuthenticationError` - will be raised on authentication problems
  + `SMBResponseException` - generic SMB failures in the response
+ `OSError` - may be raised for socket errors that I'm not catching just yet
+ `ValueError` - may be raised for invalid arguments provided

There's also a chance that any of the generic exception from dependency libraries or Python itself will be raised and I haven't caught but the above list is probably the more common ones you would see.

**Comment by Breinich** [comment]
Thank you!
