### ISSUE TITLE
Transfering files and dirs with this package

### ISSUE THREAD

**Issue by vucenovic** [jborean93/smbprotocol#35]
Hello, how would I go about transfering local files to smb shares with this package?

`source = smbclient._io.SMBDirectoryIO(filepath, 'r')
                filetTransaction = smbclient._io.SMBFileTransaction(source)
                filetTransaction.commit`

is this a viable way to do it?

**Comment by jborean93** [comment]
Have a look at the smbclient.shutil package. There are functions in there to copy a file which includes local -> remote.

**Comment by vucenovic** [comment]
Thank you, it says somehow "smbclient does not have the module shutil". 
Also, how would i go about checking if a file exists on a share? Does shutil have this property?

**Comment by jborean93** [comment]
The code for the shutil commands are at https://github.com/jborean93/smbprotocol/blob/master/smbclient/shutil.py. For your case you just want to do

```
from smbclient.shutil import copy

copy(r'source', r'dest')
```

> Also, how would i go about checking if a file exists on a share? Does shutil have this property?

Not but like `os.path` there is an [exists](https://github.com/jborean93/smbprotocol/blob/master/smbclient/path.py#L18) method in `smbclient.path`.
