### ISSUE TITLE
copy_tree tries to connect to source root

### ISSUE THREAD

**Issue by vucenovic** [jborean93/smbprotocol#36]
I'm using copytree with the following parameters for src and dst:

------------ FILEPATH ------------ (src)
T:\x\synctest\folder
------------ DESTINATION ------------ (dst)
\\IP\write_test\testroot\testdir\folder

and get the following error: ValueError: Failed to connect to 'T::445': [Errno 11001] getaddrinfo failed

However, when i use copy2 to transfer files it works.

**Comment by jborean93** [comment]
Unfortunately `copytree` does not support remote <-> local transfers while the file copy ones do. This could be a future improvement but right now it should probably check if it's a local path and give an error.

**Comment by vucenovic** [comment]
I see, unfortunetaly i really need this to work. How would I go about changing copy tree to have it support local - > remote transfer?

**Comment by jborean93** [comment]
Unfortunately you would have to either implement it in the codebase or deal with traversing the local folders and creating them on the remote and finally copying the files from local to remote.

**Comment by jborean93** [comment]
Closing as this is a feature request I have no plans on adding anytime soon. Some is free to submit a PR with the changes but please make sure that there are tests with the PR to test out the new changes.
