### ISSUE TITLE
Kerberos Authentication: Publish a new release with connection_cache argument

### ISSUE THREAD

**Issue by albertocavalcante** [jborean93/smbprotocol#43]
Hi, 

I've seen there's now an option to specify a `connection_cache`, but it's not available on the latest release available on PyPi.
Is there any plan when it should be release?

Also, if may I ask, today to authenticate using Kerberos is only required to have installed dependencies and omit username/password?

Thanks and nice project!

**Comment by jborean93** [comment]
I'm hoping to get to it soon, have been testing out https://github.com/jborean93/smbprotocol/pull/41 as much as I can to try and find any bugs before I release it to the general public.

> Also, if may I ask, today to authenticate using Kerberos is only required to have installed dependencies and omit username/password?

If you have set up the GSSAPI dependencies then you can utilise an existing Kerberos ticket for the authentication process just like Windows does for the logged in user. You can still specify explicit credentials to use for Kerberos auth, ultimately smbprotocol tries to use Kerberos and falls back to NTLM if that's unavailable.

**Comment by jborean93** [comment]
Just an FYI I've decided to skip the DFS stuff for 1.1.0 and have created an rc with the existing changes here https://pypi.org/project/smbprotocol/1.1.0rc1/. If all goes well I'm hoping to create the actual release sometime next week.

**Comment by albertocavalcante** [comment]
Thanks for the information @jborean93 !!

**Comment by jborean93** [comment]
1.1.0 has been officially released https://pypi.org/project/smbprotocol/1.1.0.
