### ISSUE TITLE
Interface is overly complex: couple of file operations takes 120 lines

### ISSUE THREAD

**Issue by sovetov** [jborean93/smbprotocol#5]
Hi,

While the project is extensible and "correct" from OOP point of view, it lacks sensible defaults and shortcuts. In the examples in this repo, it took 120 lines to open, read and delete a file. This makes the project unusable... 

It would be cool to get a file this way, for example:
```py
with Session.connect('server', 12345, 'Administrator', password) as session:
    with session.open_file('C$', '/path/to/file') as f:
        ...
```

Having only two visible entities, session and opened file, would be enough for most users. `Connection` and `TreeConnect` may be hidden. Security stuff needs more shurtcuts as it's impossible for average user to quickly come up with correct ones.

**Comment by jp495** [comment]
On a related note -- would you mind walking me through the pseudocode required to, say, retrieve the `FileName`s and `LastWriteTime`s of all files within a directory in a share?

I'm at the point where I'm connecting to the Tree just fine but running into issues querying from there. I'm new to SMB, and as well-documented as `smbprotocol` is, I'm having a hard time knowing where to start or what direction to head in.

**Comment by jborean93** [comment]
@jp495 I really do wish there was an easier way to do this but I still haven't had time to come back and revisit this. It's still definitely on my radar to fix up and I'm hoping to get back into it at some point.

For your question, I created a gist https://gist.github.com/jborean93/a3cb93fa6237012ebf587e1fbe8fc903 that will list the contents of a directory over an SMB share. These are the sort of things I wished to have a better layer over the top of smbprotocol to help abstract out the complexities of SMB for end users.

**Comment by jp495** [comment]
@jborean93 no worries! A higher level API is an easy thing to ask for when I'm not the one doing the work. I appreciate all the work you've already put into the `smbprotocol`.

And thank you for that gist. It's a huge help.

**Comment by jborean93** [comment]
Just an FYI, I've started work on this and am slowly making progress. You can see the latest status by looking at the [easy-api](https://github.com/jborean93/smbprotocol/tree/easy-api) branch. Ultimately I'm trying to replicate the builtin `os` and `shutil` modules in Python.

**Comment by jborean93** [comment]
I've finally gotten around to it and have finalised the PR to add the easy-api changes to smbprotocol. If you are interested in trying this out and need any help let me know and I'll walk you through some of it. The `smbclient` package should simplify all these operations in a major way and provide a nice an easy way to complete common file operations.

There are still things that are only accessible in the low level API of `smbprotocol` but over time these can hopefully make their way into `smbclient`.
