### ISSUE TITLE
How to close session?

### ISSUE THREAD

**Issue by 15077693d** [jborean93/smbprotocol#53]
After smbclient.register_session("server", username="user", password="pass")
How to close this session?

**Comment by jborean93** [comment]
To explicitly close the session you can run `smbclient.reset_connection_cache()`. This will close all sessions and connections that have been set up already in the global cache. If you wanted to separate a session and only close that you can create your own cache and use that in every `smbclient` call.

**Comment by 15077693d** [comment]
if i register session once, do i need to register again?

**Comment by jborean93** [comment]
Yep, the whole point of the connection cache is to register once and reuse when needed. If you do `smbclient.register_session("server", username="user", password="pass")` then every connection to `server` will be done on that registered session.
