### ISSUE TITLE
Import Error: cannot import name inquire_sec_context_by_oid

### ISSUE THREAD

**Issue by harshul1610** [jborean93/smbprotocol#6]
Hi Team, 

I am trying to run pypsexec in kerberos mode. I have installed gssapi library using pip, but when i do the following import

```
from gssapi.raw import inquire_sec_context_by_oid
```

it is failing.

Due to this HAVE_GSSAPI flag in session.py is not set, and kerberos mode is not working.

Any insights on workaround will be helpful.

**Comment by harshul1610** [comment]
- OS is linux
- ```krb5-config --version``` output is  ```Kerberos 5 release 1.6.1```
- ```ImportError: cannot import name inquire_sec_context_by_oid```. Though ```import gssapi``` works fine.

**Comment by jborean93** [comment]
What is the OS distribution? Ubuntu, Fedora, etc and it’s version?

**Comment by jborean93** [comment]
Even so, I believe your version of krb5, which implements the GSSAPI functions, is too old. The majority of the Microsoft compatibility functions and structures were added in the 1.7 release https://web.mit.edu/Kerberos/krb5-1.7/krb5-1.7.html. I can't find any changelog that explicitly referers to `gss_inquire_sec_context_by_oid` but I would assume it is 1.7. Even EL6 has 1.10.3 which supports this function.

Unfortunately there is nothing I can do here, you need to meet the requirements to be able to use Kerberos authentication. The gssapi library automatically detects if an extension is available when it is installed. If it isn't available then I cannot import the function. I need this function to support signing and encryption used by SMB.
