### ISSUE TITLE
SMBException - How can I transfer a large file? 

### ISSUE THREAD

**Issue by jintolonappan** [jborean93/smbprotocol#63]
Hi - I was trying to copy a file to SMB and encountered this error: `SMBException: The requested write length 842899 is greater than the maximum negotiated write size 65536 `

This is how I'm using it:
```py
    with open(localpath, 'rb') as src, smbclient.open_file(remotepath, mode='wb') as dst:
        dst.write(src.read())
 
```

**Comment by jborean93** [comment]
You need to buffer your writes to fix into the maximum size negotiated. There's a helper method that does just this for you.

```python
from smbclient.shutil import copyfile

copyfile(localpath, remotepath)
```

You can also use `copy` if you want to target a directory.
