### ISSUE TITLE
What is the maximum data write limit?

### ISSUE THREAD

**Issue by ashar0706** [jborean93/smbprotocol#64]
I am trying to download a very large file from a client to the remote server that I am creating using the smbclient, I break down my file into chunks, I perform the following steps:

1. Open an empty file in the remote share server
2. truncate the length of the destination file to source file length 
3. Now I want to write the chunk to their respective offset however I am unable to perform this

```
smbclient.truncate(path=destination_file_path, length=file_size)

with smbclient.open_file(path=destination_file_path, mode="ab", share_access="rw") as fd:
    fd.seek(chunk_start)
    fd.write(chunk_data_in_bytes)

```

I am able to write at most 8MBs of a data per chunk at a specified offset, when I try to write for more than 8Mb I get the following error

```
Traceback (most recent call last):
  File "/var/task/smbclient/_io.py", line 505, in write
    transaction += self.fd.write(b, offset=self._offset, send=False)
  File "/var/task/smbprotocol/open.py", line 1345, in write
    raise SMBException("The requested write length %d is greater than "
smbprotocol.exceptions.SMBException: The requested write length 20971520 is greater than the maximum negotiated write size 8388608
```

Wanted to confirm if 8MB is the write limit?

**Comment by jborean93** [comment]
There is no real default limit, the size is part of the negotiation process and returned by the server https://github.com/jborean93/smbprotocol/blob/00c1828a12c245e839eae1de85098b2750effbfe/smbprotocol/connection.py#L456-L458. You can always guarantee the limit to be 64KiB or higher. If you are wanting to get the max read/write size you can open the file in raw module like so

```python
import smbclient
import shutil

buffer = b'blah'

# buffering=0 means raw mode and there's no buffering done by Python (all on the OS level)
with open('local_path', mode='rb', buffering=0) as src_fd, smbclient.open_file(dest_path, mode='ab', share_access='rw', buffering=0) as dst_fd:
    # Use max_read_size if you want to read something from SMB
    buffer_size = dst_fd.fd.connection.max_write_size
    shutil.copyfileobj(src_fd, dst_fd, buffer_size)
```

I believe the reason why I didn't use the max_*_size attributes for `smbclient.shutil.copy()` is because while that might be the max size available the client may not have enough credits available to read/write something of that size. I've not yet fully understand the credit system used by SMB so for a stable and sane default I kept it to the max SMB packet size which should always be available.

**Comment by mas-dse-juremigi** [comment]
I am also experiencing this issue:

`smbprotocol.exceptions.SMBException: The requested write length 12633051 is greater than the maximum negotiated write size 8388608`

when using open_file.write:

`
smbprotocol.exceptions.SMBException: The requested write length 12633051 is greater than the maximum negotiated write size 8388608
`

is there a way to work around this?

**Comment by jborean93** [comment]
I've just merged in https://github.com/jborean93/smbprotocol/pull/69 which fixes this particular issue. If you attempt to write data that exceeds the negotiated max write size then multiple SMB write requests are sent. The exception to this is if you've opened the file without any buffering, `open_file(path, buffering=0, mode='wb')`. In this case it will attempt to write as much data as it can and return the number of bytes that has been written in that request. The other addition in that PR is the client will automatically calculate the max write size based on the credits that are available and try to request more credits for any subsequent write requests. It's still up to the server to grant them but at least it's not hard coded to 64KiB if it can avoid it.

As for reading data this is a bit more complicated as we are trying to avoid storing the full file in memory or even just buffering MiB of data. My recommendation if you are wanting to read as much data as possible but still do it in chunks is to do the following:

```python
with smbclient.open_file(path, mode='rb') as fd:
    while True:
        data = fd.read1(fd.raw.fd.connection.max_read_size)
        if not data:
            break

        # Do something with data
```

Calling `read1(num)` will read up to the bytes specified with only 1 SMB call. This is repeated until the end of file is reached. The benefit of this approach is that it will attempt to read up to max read size and return what it is able to get. You will need to wait until the changes in the PR have been released to use that though.

**Comment by jborean93** [comment]
Version [1.3.0](https://pypi.org/project/smbprotocol/1.3.0/) has been released on PyPI which includes this fix.
