### ISSUE TITLE
auth_protocol="kerberos" does not seem to work

### ISSUE THREAD

**Issue by grawity** [jborean93/smbprotocol#74]
By default, the module can successfully use Kerberos whenever a TGT is present -- I'm able to open files without specifying any username or password.

However, if I specifically _request_ `auth_protocol="kerberos"`, it's no longer able to connect -- I receive "Major (589824): Invalid token was supplied, Minor (100001): Success".

I'm testing against Windows Server 2019, and this happens immediately after receiving the Negotiate Protocol Response from the server.

Full backtrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/spnego/_context.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/spnego/gss.py", line 435, in step
    out_token = self._context.step(in_token)
  File "<decorator-gen-15>", line 2, in step
  File "/usr/lib/python3.9/site-packages/gssapi/_utils.py", line 155, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/usr/lib/python3.9/site-packages/gssapi/_utils.py", line 128, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/gssapi/sec_contexts.py", line 519, in step
    return self._initiator_step(token=token)
  File "/usr/lib/python3.9/site-packages/gssapi/sec_contexts.py", line 535, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 245, in gssapi.raw.sec_contexts.init_sec_context
gssapi.raw.exceptions.InvalidTokenError: Major (589824): Invalid token was supplied, Minor (100001): Success

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/smbprotocol/session.py", line 273, in connect
    out_token = context.step(in_token)
  File "/usr/lib/python3.9/site-packages/spnego/_context.py", line 91, in wrapper
    reraise(SpnegoError(base_error=native_err, context_msg=context))
  File "/usr/lib/python3.9/site-packages/spnego/_compat.py", line 60, in reraise
    raise exc
spnego.exceptions.InvalidTokenError: SpnegoError (9): Major (589824): Invalid token was supplied, Minor (100001): Success, Context: Processing security token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/smbclient/_os.py", line 362, in open_file
    raw_fd = file_class(path, mode=mode, share_access=share_access, desired_access=desired_access,
  File "/usr/lib/python3.9/site-packages/smbclient/_io.py", line 291, in __init__
    tree, fd_path = get_smb_tree(path, **kwargs)
  File "/usr/lib/python3.9/site-packages/smbclient/_pool.py", line 290, in get_smb_tree
    session = register_session(server, username=username, password=password, port=port, encrypt=encrypt,
  File "/usr/lib/python3.9/site-packages/smbclient/_pool.py", line 356, in register_session
    session.connect()
  File "/usr/lib/python3.9/site-packages/smbprotocol/session.py", line 275, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %s" % str(err.message))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (9): Major (589824): Invalid token was supplied, Minor (100001): Success, Context: Processing security token
```

**Comment by jborean93** [comment]
That’s a very interesting error but unfortunately not very helpful in trying to track down the problem.

Would you be able to share the following:

* The Linux distribution you are using
* Output of `krb5-config --version`
* The contents of the log file when you run your script with `KRB5_TRACE=/tmp/krb5.log`

If that doesn’t help we may need some logging from pyspnego to look at the raw tokens that are exchanged but we will look at that if the above doesn’t help.

**Comment by grawity** [comment]
Here's what I have:

> The Linux distribution you are using

```
$ cat /etc/os-release
NAME="Arch Linux"
ID=arch
```

> Output of `krb5-config --version`

```
$ krb5-config --version
Kerberos 5 release 1.18.3
```

> The contents of the log file when you run your script with `KRB5_TRACE=/tmp/krb5.log`

Literally nothing.

(However, I do get the expected output of "Requesting tickets" etc. when using the default smbclient parameters, so I'm sure that KRB5_TRACE itself is working as it should.)

> If that doesn’t help we may need some logging from pyspnego to look at the raw tokens that are exchanged

I'm not entirely sure how logging works in Python, but `logging.basicConfig(level=logging.DEBUG)` seems to be it?

The log with `auth_protocol="kerberos"`: [kerb.log](https://github.com/jborean93/smbprotocol/files/5903060/kerb.log)

The log with default parameters: [nego.log](https://github.com/jborean93/smbprotocol/files/5903059/nego.log)

**Comment by jborean93** [comment]
Ah ok I see the problem. The negotiate response from the server can contain an optimistic SPNEGO token that indicates what auth mechs the server supports. It is sent in as the input token to the SPNEGO handler so it can select the best auth mech from there in the normal use case. Because we are now setting Kerberos as the authentication protocol this SPNEGO token is seen as invalid hence the error. The fix would be to not send this token on the first call to the step() function when the auth protocol is not `negotiate` as the client is just ignoring what the server sends anyway.

I’m not sure how I didn’t see this in my testing but I’ll have a PR to fix this sometime tomorrow.

**Comment by jborean93** [comment]
https://github.com/jborean93/smbprotocol/pull/76 should fix this issue, if you get a chance to test it out that would be great.

Thanks for the detailed information, really helped to track down the problem.

**Comment by grawity** [comment]
Thanks, that seems to work against both Server 2019 and Samba 4.13.

**Comment by jborean93** [comment]
Thanks for the confirmation.

**Comment by jborean93** [comment]
Version 1.4.0 has been released on PyPI which includes this fix https://pypi.org/project/smbprotocol/1.4.0/.
