### ISSUE TITLE
Possible to check for locked files?

### ISSUE THREAD

**Issue by p-doyle** [jborean93/smbprotocol#75]
I'm looking for a way to determine if there are any files being actively written to a samba share server, similar to the output of the `smbstatus` command.   Is that possible with smbprotocol?   Thanks!

**Comment by jborean93** [comment]
It should be possible to do if `smbclient` exposes it, I just don’t know how without trying it. Can you give an example command and the output you get back? I should hopefully be able to run it myself and then see what SMB commands are sent to give you more info.

**Comment by p-doyle** [comment]
This is some example output from running `sudo smbstatus` on a Raspberry Pi 4 with the latest Raspbian(5.4.83-v7l+)
```
Samba version 4.9.5-Debian
PID     Username     Group        Machine                                   Protocol Version  Encryption           Signing              
----------------------------------------------------------------------------------------------------------------------------------------
6614    myuser       share_users  192.2.1.8 (ipv4:192.1.1.8:6192)     SMB3_11           -                    partial(AES-128-CMAC)

Service      pid     Machine       Connected at                     Encryption   Signing     
---------------------------------------------------------------------------------------------
IPC$         6614    192.2.1.8  Sun Jan 31 15:55:07 2021 GMT     -            -           
MyShare  6614    192.2.1.8  Sun Jan 31 15:55:07 2021 GMT     -            -           

Locked files:
Pid          Uid        DenyMode   Access      R/W        Oplock           SharePath   Name   Time
--------------------------------------------------------------------------------------------------
6614         1002       DENY_NONE  0x100081    RDONLY     NONE             /mnt/raid   .   Sun Jan 31 15:55:07 2021
6614         1002       DENY_NONE  0x100081    RDONLY     NONE             /mnt/raid   .   Sun Jan 31 15:55:07 2021
6614         1002       DENY_ALL   0x100080    RDONLY     NONE             /mnt/raid   .   Sun Jan 31 15:55:08 2021
```

I believe [this](https://github.com/samba-team/samba/blob/master/source3/utils/status.c) is the source, though I don't know how that relates to smbclient... sorry if that's not much help.

**Comment by jborean93** [comment]
No worries, thanks for the output. When I get some time I'll try and run it myself and see what is involved.

**Comment by jborean93** [comment]
Hmm a read of the man page seems to indicate `smbstatus` gets the status of locked files on the local Samba instance and not on the remote one. Can `smbstatus` be used to get locked files on a remote server, if not then `smbprotocol` can't really do what you want as it's purely a client implementation.

**Comment by p-doyle** [comment]
Ah okay, my apologies, thanks!
