### ISSUE TITLE
Any way to check for or handle connection errors while manipulating files?

### ISSUE THREAD

**Issue by zuroh** [jborean93/smbprotocol#78]
I have a scenario where i am writing files to a remote SMB share, however I would like to handle a case where the file writing stops and exception is raised when the connection between the two machines are interrupted for example. Currently the program just freezes and no exception is raised when this happens. I have also tried to execute the writing of file to SMB share in a separate thread and call that thread with a timeout but that doesn't seem to work either. 

Is there anyway to handle this issue?

I am connecting from a windows client to a linux server over local area network. 

```
import time
import smbclient
import threading
import _thread

class timeout():


    def __init__(self, time):
        self.time = time
        self.exit = False

    def __enter__(self):
        threading.Thread(target=self.callme).start()

    def callme(self):
        time.sleep(self.time)
        if self.exit == False:
            _thread.interrupt_main()  

    def __exit__(self, a, b, c):
        self.exit = True


with timeout(20):
    try:
        while True:
            time.sleep(0.3)
            try:
                smbclient.stat(
                    somefilehere)
            except Exception as e:
                print(e)
            print("done inner")
    except KeyboardInterrupt:
        print("done outer")
```

**Comment by jborean93** [comment]
It should be raising the exception but it sounds like there is some bad logic in the connection handler that causes it to ignore and just perpetually wait in the background. This layer is quite complex as it uses a background thread to read from the socket and another thread to process those messages. Ultimately the bug needs to be found and fixed.

**Comment by jborean93** [comment]
I've just opened https://github.com/jborean93/smbprotocol/pull/80 which exposes the `SMBConnectionClosed` that is raised on any connection errors. You should be able to catch this and retry for as long as you desire. It should also fix the freezes but it would be great if you could test it out and see if it works for you.

**Comment by zuroh** [comment]
Thank you! I'll test it soon as I'm free and get back to you with the results.

**Comment by zuroh** [comment]
Hi there, I did some testing with version 1.5.0

I found that if the connection is closed on the client's side, the exception is thrown almost instantly and it works as expected.

However if the connection is closed on the server side, then the exception takes around 12-15 seconds and very occasionally still hangs. 

Both give the same exception message
// SMB socket was closed, cannot send or receive any more data

Luckily for my use case i only needed to check the connection being closed on the client side. But out of curiosity is there a reason for the delay? Is there some sort of manual timeout value to manipulate?

**Comment by jborean93** [comment]
Thanks for testing it and sharing this information is really helps. I'm not sure why a close on the server side would still take 12-15 seconds. The only timeout that occurs is based on 10 minutes so if the socket had closed but the smbprotocol code wasn't notified I would expect it to last ~10 minutes before an exception is raised. It does worry me that there are still occasional hangs and I hope we will be able to track it down.

How are you replicating the closing of the socket on the server side? I thought I was at least testing the socket side failures on both a client and server side close/shutdown with https://github.com/jborean93/smbprotocol/pull/80/files#diff-3fa04edb535301836d70c76c3496eff4b20a004bb7e7594986194b61cd9aadbfR141-R176. While this is a very small example and it sounds like there's more going on outside this code, these tests make sure that the `recv()` function returns `b''` (used to denote the closing of the socket) when it is shutdown by either the client or server.

**Comment by zuroh** [comment]
Hi there, my method of testing was much more primitive, what i did was to simulate an actual use case where both client and servers are in the same local area network, the client then sends many small files continuously with an interval of 0.1 seconds sleep between each file send. Each file is around 100KB in size. 

I then switched off the wifi/ethernet interface of client/server side connection while the script to write files was ongoing to simulate the event of network loss while file sending. Hope this helps.

**Comment by jborean93** [comment]
Thanks for the extra info, could you try out the following and turn off the network interface like you do for your other tests. I'm interested to see if `recv()` returns straight away with `b''` or an exception or whether it also hangs for the 12-15 second mark.

```python
import socket

sock = socket.create_connection(('ip address', 445))
sock.settimeout(None)
sock.recv(4)
```

**Comment by zuroh** [comment]
Not sure if relevant, client is a windows machine and server is a mac

1. Switch off client network interface and run the program immediately returns: 
 `OSError: [WinError 10051] A socket operation was attempted to an unreachable network`
which is expected.

2. Run the program then switch off client network, program immediately returns:
`ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine` 

3. Switch off server network and run the program on client side:
`TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because 
connected host has failed to respond`
This error message took around 25-30 seconds, it was different each time i tested it. 

4. Run the program then switch off server network:
Program hangs, I did not bother to wait the 10 minutes. Interestingly i noted that if i again turned on the server side connection while it is in this hanging state, the program terminates with no error message after about 20 seconds from switching on the network connection.

**Comment by jborean93** [comment]
Scenario 3 is a connection timeout which we currently have set to 60 seconds. There doesn't seem to be a way to define this in the `ClientConfig()` globally for the high level API but it is a supported kwargs under [connection_timeout](https://github.com/jborean93/smbprotocol/blob/b72b4c7d1544b28c0d6f4b30b108d21650292be7/smbclient/_pool.py#L321). I'm surprised it's only 25-30 seconds as the default is `60`.

Scenario 4 looks to be a critical failure when the client does not receive a `FIN` or `ACK` from the server causing it to always see the connection as online. I've been able to replicate this behaviour for both blocking and non-blocking sockets when turning a libvirt interface off. All the calls, `sock.send()`, `sock.recv(n)`, and `select([sock], [], [])` all hang indefinitely even though the interface is no longer present. I have no idea why it's still there as the actual network interface is no longer present on the client but I don't see any way around this. It does sound like we need a more sane timeout when sending and waiting for a response but the way the current API is set out makes that hard to inject. Potentially I need to enable TCP Keep-Alive but that does not seem to be portable across platforms so I'll have to keep this in mind for future releases.

I appreciate the time and effort you've put into testing all this and I'm fairly confident the code in the PR helps with normal socket shutdown and closures from both the client and server side. It seems like there is still some more work that can be done to handle abnormal interrupts which I'll try to look into in the future.
