### ISSUE TITLE
Unhelpful exception on locked out account / incorrect password

### ISSUE THREAD

**Issue by jozzas** [jborean93/smbprotocol#79]
smbprotocol ==1.4.0

When attempting to `register_session`,  if the user account used to authenticate is locked out or an incorrect password is specified, the following exception is thrown:

    smbclient.register_session(server, username=username, password=password)
      File "lib\site-packages\smbclient\_pool.py", line 359, in register_session
        session.connect()
      File "lib\site-packages\smbprotocol\session.py", line 292, in connect
        response = self.connection.receive(request)
      File "lib\site-packages\smbprotocol\connection.py", line 617, in wrapped
        return func(self, *args, **kwargs)
      File "lib\site-packages\smbprotocol\connection.py", line 931, in receive
        raise SMBResponseException(response)
    smbprotocol.exceptions.SMBResponseException: Received unexpected status from the server: Unknown error. (3221225578) UNKNOWN_ENUM: 0xc000006a

I'm not sure if there's something more meaningful that can be done with this, but we've encountered it both when an incorrect password was attempted, and when the correct password was attempted but the user was locked out.

We're catching similar errors for now and logging a hint that there may be an account issue. Let me know if I can provide any additional info.

**Comment by jborean93** [comment]
SMB header responses just return a status code, in this case `3221225578`, and it's up the client to interpret it correctly. Luckily these status codes typically correspond to the [NtStatus values](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) in this case the `STATUS_WRONG_PASSWORD` value.

To turn this into a more readable error message you need to add the code to the [NtStatus](https://github.com/jborean93/smbprotocol/blob/master/smbprotocol/header.py#L51) definition and add a custom exception to [exception.py](https://github.com/jborean93/smbprotocol/blob/master/smbprotocol/exceptions.py).

You can see this for [STATUS_ACCESS_DENIED](https://github.com/jborean93/smbprotocol/blob/master/smbprotocol/header.py#L75) with the corresponding exception [AccessDenied](https://github.com/jborean93/smbprotocol/blob/b72b4c7d1544b28c0d6f4b30b108d21650292be7/smbprotocol/exceptions.py#L361-L363). This is unfortunately all a manual effort as there are numerous status values that may be applicable to SMB and I just add them as I encounter them.
