### ISSUE TITLE
Fallback to SMB1

### ISSUE THREAD

**Issue by Franky1** [jborean93/smbprotocol#88]
As far as i understand only SMB2+ is supported?
Any chance for SMB1 support?
There are still devices (home network routers...) that only supports SMB1
Have tried a samba connection with my router to no avail, I guess it only supports SMB1 and I always get:

```log
raise SMBConnectionClosed('SMB socket was closed, cannot send or receive any more data')
```

**Comment by jborean93** [comment]
No chance sorry, SMB 1 is a different protocol with a different set of messages. It’s also full of security flaws and I have no desire to contribute to its continued existence.
