### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by dHannasch** [jborean93/smbprotocol#94]
Should smbprotocol drop support for Python 2?
(https://www.python.org/doc/sunset-python-2/)

**Comment by jborean93** [comment]
While I'm happy to drop Python 2.7 I probably won't drop it until there is a need to not actually use it. Right now I use it in a few places where Python 2.7 is being used so still being able to do bugfixes for that version is helpful.

**Comment by jborean93** [comment]
Your wish has been granted with https://github.com/jborean93/smbprotocol/pull/104 :)
